In [1]:
import pickle
import random
import heapq
from collections import deque
from pathlib import Path
import pandas as pd
import game_logic
import pyarrow

In [4]:
pd.read_parquet('../data/english_movies_with_box_office.parquet')

,tconst,personIds,originalTitle,startYear,box_office_x,box_office_y
0,tt0035423,"nm0043662,nm0118806,nm0126148,nm0179296,nm0294...",Kate & Leopold,2001.0,76019048,76019048
1,tt0036606,"nm0028791,nm0336942,nm0426834,nm0485392,nm0517...","Another Time, Another Place",1983.0,0,0
2,tt0042423,"nm0120684,nm0305239,nm0340563,nm0365092,nm0367...",The Dungeon of Harrow,1964.0,0,0
3,tt0044932,"nm1214148,nm2088491,nm5648446,nm7784675",Out of the Shadow,1961.0,0,0
4,tt0049079,"nm0579230,nm0897763",Una cita de amor,1958.0,0,0
...,...,...,...,...,...,...
83152,tt9908448,"nm10547143,nm3133401,nm3483889",The Bells of Hell,2018.0,0,0
83153,tt9908636,"nm10319155,nm10319156,nm10319158,nm10319161,nm...",Das Spiel der Hoffnung,2017.0,0,0
83154,tt9911046,"nm10536355,nm10536356,nm10536357,nm10536358,nm...",The Saving,2020.0,0,0
83155,tt9913660,"nm10175558,nm10209518,nm1067844,nm11900816,nm1...",No Apology,2019.0,0,0
83156,tt9916190,"nm10385419,nm10430118,nm10676018,nm11045562,nm...",Safeguard,2020.0,0,0

In [11]:
pd.read_parquet('../data/actor_names.parquet')

,nconst,primaryName,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0117057"
2,nm0000003,Brigitte Bardot,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"
...,...,...,...,...
2204110,nm9993663,Max Thursam,"actor,miscellaneous","tt8606950,tt10709768"
2204111,nm9993680,Christopher-Lawson Palmer,actor,"tt8295580,tt21745568,tt10427366,tt21047844"
2204112,nm9993693,Apsara Rani,"actress,archive_footage","tt12856788,tt39440956,tt13847502,tt8302382"
2204113,nm9993694,Chinmay Mishra,"actor,director,producer","tt18361688,tt18687502,tt8737752,tt9083282"
2204114,nm9993703,James Craigmyle,actor,"tt11212278,tt6914160,tt6225166,tt10627062"

In [24]:
df.sort_values('box_office_x', ascending=False).head(10)

,tconst,personIds,originalTitle,startYear,box_office_x,box_office_y
30136,tt0499549,"nm0000035,nm0000244,nm0000610,nm0001634,nm0002...",Avatar,2009.0,2923706026,2923706026
69942,tt4154796,"nm0000375,nm0000982,nm0002853,nm0005566,nm0014...",Avengers: Endgame,2019.0,2799439100,2799439100
45949,tt1630029,"nm0002332,nm0043063,nm0046843,nm0054308,nm0077...",Avatar: The Way of Water,2022.0,2353096253,2353096253
14810,tt0120338,"nm0000035,nm0000138,nm0000701,nm0000708,nm0000...",Titanic,1997.0,2264162353,2264162353
56559,tt2488496,"nm0000355,nm0004198,nm0004361,nm0009181,nm0026...",Star Wars: Episode VII - The Force Awakens,2015.0,2068223624,2068223624
69941,tt4154756,"nm0000982,nm0014884,nm0064348,nm0090309,nm0094...",Avengers: Infinity War,2018.0,2052415039,2052415039
34210,tt10872600,"nm0002006,nm0004855,nm0005391,nm0032126,nm0041...",Spider-Man: No Way Home,2021.0,1921847111,1921847111
57507,tt26443597,"nm0145614,nm0308199,nm0327056,nm0329481,nm0363...",Zootopia 2,2025.0,1848521131,1848521131
53384,tt22022452,"nm0005323,nm0267010,nm0395864,nm0415798,nm0528...",Inside Out 2,2024.0,1698863816,1698863816
25950,tt0369610,"nm0000352,nm0000703,nm0004746,nm0014380,nm0029...",Jurassic World,2015.0,1671537444,1671537444

In [3]:
game_logic.build_and_save('../data/english_movies_with_box_office.parquet', '../data/actor_names.parquet', '../data/game_data.pkl')

[build_and_save] Saved 11410 movies and 234376 actors → ../data/game_data.pkl

{'movies': {'tt0035423': {'title': 'Kate & Leopold (2001)',
   'box_office': 76019048.0,
   'actor_ids': ['nm0043662',
    'nm0118806',
    'nm0126148',
    'nm0179296',
    'nm0294961',
    'nm0298855',
    'nm0336960',
    'nm0374011',
    'nm0413087',
    'nm0609169',
    'nm0697069',
    'nm0715900',
    'nm0745645',
    'nm0762615',
    'nm0782395',
    'nm0870560',
    'nm0925717',
    'nm1005572',
    'nm1036165',
    'nm1054485',
    'nm1094252',
    'nm1095749',
    'nm1096243',
    'nm1097358',
    'nm1098807',
    'nm1099254',
    'nm1100325',
    'nm1101081',
    'nm1101376',
    'nm1101423',
    'nm1101521',
    'nm1101736',
    'nm1101904',
    'nm1102242',
    'nm1102425',
    'nm1103596']},
  'tt0051360': {'title': 'Andy Hardy Comes Home (1958)',
   'box_office': 610000.0,
   'actor_ids': ['nm0060924', 'nm0147223', 'nm0919320']},
  'tt0051380': {'title': 'Attack of the 50 Foot Woman (1958)',
   'box_office': 480000.0,
   'actor_ids': ['nm0153759',
    'nm0235060',
    'nm0330574',
    'nm0360221',
    'nm0370886',
    'nm0399989',
    'nm0743681',
    'nm0828382',
    'nm0855827',
    'nm0896035',
    'nm0907170']},
  'tt0051393': {'title': 'The Badlanders (1958)',
   'box_office': 2015000.0,
   'actor_ids': ['nm0446279', 'nm1081879']},
  'tt0051411': {'title': 'The Big Country (1958)',
   'box_office': 3500000.0,
   'actor_ids': ['nm0004647',
    'nm0010928',
    'nm0066166',
    'nm0168035',
    'nm0412322',
    'nm0571173',
    'nm0604501',
    'nm0847970']},
  'tt0051418': {'title': 'The Blob (1958)',
   'box_office': 4000000.0,
   'actor_ids': ['nm0021982',
    'nm0053587',
    'nm0072536',
    'nm0094965',
    'nm0100083',
    'nm0138453',
    'nm0153679',
    'nm0181080',
    'nm0184103',
    'nm0192863',
    'nm0214424',
    'nm0276341',
    'nm0291133',
    'nm0314159',
    'nm0358451',
    'nm0364796',
    'nm0438939',
    'nm0444970',
    'nm0510989',
    'nm0582399',
    'nm0582406',
    'nm0644646',
    'nm0653841',
    'nm0665727',
    'nm0709909',
    'nm0741859',
    'nm0746505',
    'nm0754663',
    'nm0800796',
    'nm0808112',
    'nm0845929',
    'nm1080118',
    'nm2904177']},
  'tt0051429': {'title': 'Bonjour tristesse (1958)',
   'box_office': 13200000.0,
   'actor_ids': ['nm0264151', 'nm0755982']},
  'tt0051459': {'title': 'Cat on a Hot Tin Roof (1958)',
   'box_office': 17570324.0,
   'actor_ids': ['nm0000072',
    'nm0000752',
    'nm0007217',
    'nm0309588',
    'nm0412322',
    'nm0792828',
    'nm0853299',
    'nm0918318',
    'nm0931783']},
  'tt0051496': {'title': 'Cowboy (1958)',
   'box_office': 1600000.0,
   'actor_ids': ['nm0440542', 'nm0948685']},
  'tt0051500': {'title': 'The Cry Baby Killer (1958)',
   'box_office': 600000.0,
   'actor_ids': ['nm0277240',
    'nm0286176',
    'nm0436049',
    'nm0461756',
    'nm0589808',
    'nm0593198',
    'nm0917237']},
  'tt0051542': {'title': 'Corridors of Blood (1958)',
   'box_office': 51500.0,
   'actor_ids': ['nm0391286', 'nm0738635']},
  'tt0051554': {'title': 'Dracula (1958)',
   'box_office': 3500000.0,
   'actor_ids': ['nm0001088',
    'nm0033636',
    'nm0072498',
    'nm0225487',
    'nm0269668',
    'nm0310152',
    'nm0391143',
    'nm0550515',
    'nm0581416',
    'nm0655436',
    'nm0834320',
    'nm0886881',
    'nm0940161']},
  'tt0051622': {'title': 'The Fly (1958)',
   'box_office': 3000000.0,
   'actor_ids': ['nm0003339',
    'nm0314867',
    'nm0373314',
    'nm0378517',
    'nm0654433']},
  'tt0051658': {'title': 'Gigi (1958)',
   'box_office': 13200000.0,
   'actor_ids': ['nm0001989',
    'nm0002001',
    'nm0006238',
    'nm0007995',
    'nm0074405',
    'nm0320006',
    'nm0333352',
    'nm0419978',
    'nm0431139',
    'nm0517350']},
  'tt0051745': {'title': 'Houseboat (1958)',
   'box_office': 3500000.0,
   'actor_ids': ['nm0317127',
    'nm0345340',
    'nm0378517',
    'nm0405054',
    'nm0676928']},
  'tt0051754': {'title': 'I Accuse! (1958)',
   'box_office': 665000.0,
   'actor_ids': ['nm0151499', 'nm0407810']},
  'tt0051885': {'title': 'Macabre (1958)',
   'box_office': 5000000.0,
   'actor_ids': ['nm0244635', 'nm0345630', 'nm0388918']},
  'tt0052050': {'title': 'Party Girl (1958)',
   'box_office': 2380000.0,
   'actor_ids': ['nm0361016',
    'nm0446279',
    'nm0485687',
    'nm0574686',
    'nm0880280']},
  'tt0052097': {'title': 'The Proud Rebel (1958)',
   'box_office': 1500000.0,
   'actor_ids': ['nm0480454', 'nm0591768', 'nm1873420']},
  'tt0052225': {'title': 'South Pacific (1958)',
   'box_office': 36800000.0,
   'actor_ids': ['nm0007323',
    'nm0007961',
    'nm0047316',
    'nm0048458',
    'nm0074777',
    'nm0084134',
    'nm0106387',
    'nm0111012',
    'nm0114612',
    'nm0124179',
    'nm0129459',
    'nm0129856',
    'nm0164153',
    'nm0165172',
    'nm0194023',
    'nm0198980',
    'nm0200445',
    'nm0205636',
    'nm0208063',
    'nm0209597',
    'nm0226840',
    'nm0232066',
    'nm0239401',
    'nm0257486',
    'nm0275102',
    'nm0285637',
    'nm0287936',
    'nm0301928',
    'nm0310989',
    'nm0345933',
    'nm0355765',
    'nm0363448',
    'nm0398783',
    'nm0414603',
    'nm0434711',
    'nm0443128',
    'nm0449734',
    'nm0457164',
    'nm0485044',
    'nm0490871',
    'nm0496939',
    'nm0517660',
    'nm0526271',
    'nm0530241',
    'nm0543833',
    'nm0564213',
    'nm0585151',
    'nm0625185',
    'nm0638395',
    'nm0660456',
    'nm0661582',
    'nm0693530',
    'nm0767246',
    'nm0780721',
    'nm0799754',
    'nm0809703',
    'nm0810296',
    'nm0821082',
    'nm0859129',
    'nm0870366',
    'nm0881477',
    'nm0907782',
    'nm0908588',
    'nm0913551',
    'nm0928059',
    'nm0949598',
    'nm1030126',
    'nm1060636',
    'nm1088363',
    'nm11639210',
    'nm1201179',
    'nm1248614',
    'nm1343656',
    'nm1521367',
    'nm1813301',
    'nm2063998',
    'nm2072300',
    'nm2092100',
    'nm2092340',
    'nm2092607',
    'nm2092891',
    'nm2093227',
    'nm2093287',
    'nm2093311',
    'nm2093607',
    'nm2093663',
    'nm2093877',
    'nm2093919',
    'nm2093962',
    'nm2093987',
    'nm2094061',
    'nm2094167',
    'nm2094247',
    'nm2094489',
    'nm2094593',
    'nm2094632',
    'nm2094954',
    'nm2095151',
    'nm2095238',
    'nm2095280',
    'nm2095325',
    'nm2095331',
    'nm2095414',
    'nm2095562',
    'nm2095601',
    'nm2095655',
    'nm2095821',
    'nm2095837',
    'nm2095933',
    'nm2095945',
    'nm2095954',
    'nm2096025',
    'nm2096055',
    'nm2096410',
    'nm2096522',
    'nm2096635',
    'nm2096922',
    'nm2096954',
    'nm2096995',
    'nm2097401',
    'nm2097621',
    'nm2097775',
    'nm2097896',
    'nm2097956',
    'nm2098147',
    'nm2098621',
    'nm2099015',
    'nm2099458',
    'nm2099766',
    'nm2100085',
    'nm2100370',
    'nm2100504',
    'nm2100520',
    'nm2100758',
    'nm2100943',
    'nm2101669',
    'nm2101675',
    'nm2101919',
    'nm2102126',
    'nm2102376',
    'nm2102488',
    'nm2102954',
    'nm2103082',
    'nm2104121',
    'nm2104392',
    'nm2105286',
    'nm2105361',
    'nm2105371',
    'nm2296356',
    'nm3361889',
    'nm3364664',
    'nm3365077',
    'nm3373500',
    'nm3373756',
    'nm3423354',
    'nm3984575',
    'nm5253477',
    'nm9440037']},
  'tt0052311': {'title': 'Touch of Evil (1958)',
   'box_office': 2247500.0,
   'actor_ids': ['nm0000017',
    'nm0000032',
    'nm0000080',
    'nm0001248',
    'nm0001463',
    'nm0130407',
    'nm0133778',
    'nm0172615',
    'nm0182447',
    'nm0212037',
    'nm0367677',
    'nm0426006',
    'nm0450255',
    'nm0487103',
    'nm0513009',
    'nm0543072',
    'nm0587637',
    'nm0590123',
    'nm0601369',
    'nm0636364',
    'nm0727893',
    'nm0765132',
    'nm0788288',
    'nm0792549',
    'nm0848667',
    'nm0915840']},
  'tt0052336': {'title': 'Underwater Warrior (1958)',
   'box_office': 405000.0,
   'actor_ids': ['nm0266710', 'nm0383049', 'nm0511423', 'nm0663703']},
  'tt0052357': {'title': 'Vertigo (1958)',
   'box_office': 7808900.0,
   'actor_ids': ['nm0000071',
    'nm0000895',
    'nm0001571',
    'nm0002136',
    'nm0009567',
    'nm0013242',
    'nm0016054',
    'nm0023649',
    'nm0047450',
    'nm0051214',
    'nm0053569',
    'nm0056269',
    'nm0093770',
    'nm0093806',
    'nm0106130',
    'nm0120317',
    'nm0143019',
    'nm0179289',
    'nm0194728',
    'nm0207918',
    'nm0251460',
    'nm0257274',
    'nm0264675',
    'nm0269977',
    'nm0277825',
    'nm0289931',
    'nm0314383',
    'nm0343861',
    'nm0359832',
    'nm0375738',
    'nm0380311',
    'nm0428216',
    'nm0481196',
    'nm0536435',
    'nm0555336',
    'nm0558826',
    'nm0577956',
    'nm0591468',
    'nm0605291',
    'nm0633532',
    'nm0665886',
    'nm0667548',
    'nm0681330',
    'nm0691732',
    'nm0692487',
    'nm0695206',
    'nm0699602',
    'nm0701345',
    'nm0726086',
    'nm0739518',
    'nm0774024',
    'nm0776123',
    'nm0778150',
    'nm0778156',
    'nm0790164',
    'nm0812762',
    'nm0823716',
    'nm0869245',
    'nm0873859',
    'nm0874576',
    'nm0919472',
    'nm0920078',
    'nm0937760',
    'nm0955120',
    'nm0959297',
    'nm1042104',
    'nm1073198',
    'nm1285984',
    'nm13765458',
    'nm1908176',
    'nm1908573',
    'nm2366368',
    'nm2517913',
    'nm2990218',
    'nm3389102',
    'nm3924356',
    'nm3999860',
    'nm6772472',
    'nm7261841']},
  'tt0052365': {'title': 'The Vikings (1958)',
   'box_office': 20311.0,
   'actor_ids': ['nm0006209',
    'nm0041602',
    'nm0118480',
    'nm0175403',
    'nm0232019',
    'nm0324576',
    'nm0553862',
    'nm0629563',
    'nm0861930',
    'nm0915427']},
  'tt0052543': {'title': 'Al Capone (1959)',
   'box_office': 2500000.0,
   'actor_ids': ['nm0153083', 'nm0211460']},
  'tt0052561': {'title': 'Anatomy of a Murder (1959)',
   'box_office': 8000000.0,
   'actor_ids': ['nm0000071',
    'nm0000781',
    'nm0001262',
    'nm0001665',
    'nm0035680',
    'nm0063632',
    'nm0114612',
    'nm0132186',
    'nm0254153',
    'nm0335497',
    'nm0358069',
    'nm0366627',
    'nm0444012',
    'nm0494661',
    'nm0528373',
    'nm0573830',
    'nm0640023',
    'nm0695937',
    'nm0712844',
    'nm0743364',
    'nm0914103',
    'nm0919583',
    'nm0921959',
    'nm0923268']},
  'tt0052610': {'title': 'The Beat Generation (1959)',
   'box_office': 750000.0,
   'actor_ids': ['nm0152224',
    'nm0176438',
    'nm0188973',
    'nm0199846',
    'nm0351918',
    'nm0564695',
    'nm1366377']},
  'tt0052618': {'title': 'Ben-Hur (1959)',
   'box_office': 164000000.0,
   'actor_ids': ['nm0000032',
    'nm0000067',
    'nm0000963',
    'nm0029515',
    'nm0037309',
    'nm0051214',
    'nm0054191',
    'nm0079335',
    'nm0124375',
    'nm0128405',
    'nm0134831',
    'nm0134993',
    'nm0144360',
    'nm0162242',
    'nm0181085',
    'nm0188133',
    'nm0190595',
    'nm0192958',
    'nm0207172',
    'nm0224078',
    'nm0238581',
    'nm0248283',
    'nm0257269',
    'nm0273102',
    'nm0311165',
    'nm0331495',
    'nm0341518',
    'nm0361823',
    'nm0370144',
    'nm0375216',
    'nm0415488',
    'nm0427230',
    'nm0471177',
    'nm0519281',
    'nm0544275',
    'nm0545461',
    'nm0586823',
    'nm0603048',
    'nm0603682',
    'nm0609731',
    'nm0622993',
    'nm0623056',
    'nm0640732',
    'nm0654025',
    'nm0667611',
    'nm0718835',
    'nm0754563',
    'nm0779549',
    'nm0824284',
    'nm0848451',
    'nm0857457',
    'nm0861930',
    'nm0862366',
    'nm0906040',
    'nm0928741',
    'nm0935988',
    'nm0943758',
    'nm1197365',
    'nm1403175',
    'nm1945505',
    'nm2079025',
    'nm3291374',
    'nm8404957']},
  'tt0052655': {'title': 'A Bucket of Blood (1959)',
   'box_office': 180000.0,
   'actor_ids': ['nm0051398',
    'nm0109612',
    'nm0123620',
    'nm0123630',
    'nm0136147',
    'nm0368479',
    'nm0606371',
    'nm0832478',
    'nm0883205']},
  'tt0052700': {'title': 'Compulsion (1959)',
   'box_office': 1800000.0,
   'actor_ids': ['nm0226947', 'nm0505670', 'nm0520968']},
  'tt0052847': {'title': 'Gidget (1959)',
   'box_office': 1500000.0,
   'actor_ids': ['nm0000364',
    'nm0048587',
    'nm0201626',
    'nm0255056',
    'nm0313617',
    'nm0437408',
    'nm0488427',
    'nm0582401',
    'nm0607507',
    'nm1571014']},
  'tt0052948': {'title': 'Journey to the Center of the Earth (1959)',
   'box_office': 10000000.0,
   'actor_ids': ['nm0004769',
    'nm0006428',
    'nm0012113',
    'nm0203076',
    'nm0505610',
    'nm0740164']},
  'tt0052950': {'title': 'The Journey (1959)',
   'box_office': 19873.0,
   'actor_ids': ['nm0206815',
    'nm0270223',
    'nm0413271',
    'nm0548240',
    'nm0701491',
    'nm0843907',
    'nm0881635',
    'nm0902744']},
  'tt0052969': {'title': 'The Killer Shrews (1959)',
   'box_office': 1000000.0,
   'actor_ids': ['nm0078940',
    'nm0221549',
    'nm0243418',
    'nm0332141',
    'nm0525885',
    'nm0572741']},
  'tt0053125': {'title': 'North by Northwest (1959)',
   'box_office': 13275000.0,
   'actor_ids': ['nm0000051',
    'nm0001445',
    'nm0001693',
    'nm0001991',
    'nm0002136',
    'nm0005978',
    'nm0006085',
    'nm0006192',
    'nm0083081',
    'nm0177642',
    'nm0194373',
    'nm0226165',
    'nm0254006',
    'nm0292385',
    'nm0294838',
    'nm0333352',
    'nm0346867',
    'nm0389152',
    'nm0404360',
    'nm0414272',
    'nm0427230',
    'nm0460238',
    'nm0484829',
    'nm0517350',
    'nm0528373',
    'nm0558938',
    'nm0574686',
    'nm0582869',
    'nm0643211',
    'nm0643945',
    'nm0679538',
    'nm0686857',
    'nm0774413',
    'nm0776833',
    'nm0776858',
    'nm0777696',
    'nm0871710',
    'nm0871876',
    'nm0878369',
    'nm0906662',
    'nm0929965',
    'nm1024679',
    'nm1261228',
    'nm1289046',
    'nm2465478',
    'nm2652389']},
  'tt0053131': {'title': "The Nun's Story (1959)",
   'box_office': 12800000.0,
   'actor_ids': ['nm0098382',
    'nm0262725',
    'nm0424159',
    'nm0467831',
    'nm0833152']},
  'tt0053137': {'title': 'On the Beach (1959)',
   'box_office': 2200000.0,
   'actor_ids': ['nm0001257',
    'nm0025997',
    'nm0107339',
    'nm0112119',
    'nm0120063',
    'nm0230934',
    'nm0566538',
    'nm0570205',
    'nm0576818',
    'nm0602943',
    'nm0851149',
    'nm0852425',
    'nm0894693',
    'nm0915594',
    'nm2558167']},
  'tt0053143': {'title': 'Operation Petticoat (1959)',
   'box_office': 6800000.0,
   'actor_ids': ['nm0262775',
    'nm0321143',
    'nm0339615',
    'nm0526693',
    'nm0581277',
    'nm0605901',
    'nm0639613',
    'nm0765102',
    'nm0800359']},
  'tt0053172': {'title': 'Pillow Talk (1959)',
   'box_office': 18750000.0,
   'actor_ids': ['nm0000013',
    'nm0001369',
    'nm0021134',
    'nm0066494',
    'nm0085945',
    'nm0330456',
    'nm0403022',
    'nm0484653',
    'nm0574961',
    'nm0635839',
    'nm0672576',
    'nm0709704',
    'nm0713170',
    'nm0835649']},
  'tt0053182': {'title': 'Porgy and Bess (1959)',
   'box_office': 3500000.0,
   'actor_ids': ['nm0006024',
    'nm0011694',
    'nm0040984',
    'nm0047440',
    'nm0133778',
    'nm0199268',
    'nm0244292',
    'nm0283314',
    'nm0293581',
    'nm0322658',
    'nm0354381',
    'nm0413477',
    'nm0482849',
    'nm0543072',
    'nm0560046',
    'nm0563811',
    'nm0635560',
    'nm0779483',
    'nm0788128',
    'nm0858103',
    'nm0870078',
    'nm0933391']},
  'tt0053221': {'title': 'Rio Bravo (1959)',
   'box_office': 5750000.0,
   'actor_ids': ['nm0001141',
    'nm0001509',
    'nm0015391',
    'nm0327602',
    'nm0625699',
    'nm0735310',
    'nm0751245']},
  'tt0053271': {'title': 'The Shaggy Dog (1959)',
   'box_office': 17658000.0,
   'actor_ids': ['nm0794956', 'nm0923268']},
  'tt0053285': {'title': 'Sleeping Beauty (1959)',
   'box_office': 51600000.0,
   'actor_ids': ['nm0005980',
    'nm0006066',
    'nm0019286',
    'nm0020289',
    'nm0041598',
    'nm0124390',
    'nm0182250',
    'nm0204618',
    'nm0271658',
    'nm0310583',
    'nm0392067',
    'nm0434724',
    'nm0493546',
    'nm0524853',
    'nm0533972',
    'nm0633875',
    'nm0639649',
    'nm0710996',
    'nm0737843',
    'nm0794301',
    'nm0796294',
    'nm0812703',
    'nm0859892',
    'nm0942723',
    'nm2335540',
    'nm2758815',
    'nm8904567']},
  'tt0053290': {'title': 'Solomon and Sheba (1959)',
   'box_office': 12200000.0,
   'actor_ids': ['nm0026876',
    'nm0222831',
    'nm0294393',
    'nm0518178',
    'nm0667542',
    'nm0671559']},
  'tt0053291': {'title': 'Some Like It Hot (1959)',
   'box_office': 25000000.0,
   'actor_ids': ['nm0000054',
    'nm0000348',
    'nm0000493',
    'nm0002285',
    'nm0016054',
    'nm0021893',
    'nm0057969',
    'nm0062896',
    'nm0076005',
    'nm0086994',
    'nm0113873',
    'nm0124375',
    'nm0134993',
    'nm0136265',
    'nm0142481',
    'nm0153481',
    'nm0180115',
    'nm0207068',
    'nm0233576',
    'nm0237634',
    'nm0278554',
    'nm0281004',
    'nm0336475',
    'nm0346895',
    'nm0385019',
    'nm0473223',
    'nm0509780',
    'nm0516619',
    'nm0540338',
    'nm0553361',
    'nm0558285',
    'nm0563417',
    'nm0598198',
    'nm0625726',
    'nm0639366',
    'nm0654025',
    'nm0655642',
    'nm0664701',
    'nm0675490',
    'nm0685609',
    'nm0695716',
    'nm0706368',
    'nm0732340',
    'nm0741876',
    'nm0746978',
    'nm0761099',
    'nm0767194',
    'nm0776711',
    'nm0776833',
    'nm0790064',
    'nm0800563',
    'nm0831889',
    'nm0858329',
    'nm0858412',
    'nm0876938',
    'nm0932617',
    'nm0933489',
    'nm10092918',
    'nm1009401',
    'nm1403175',
    'nm1406177',
    'nm1410217',
    'nm1688661',
    'nm1798478',
    'nm3667530',
    'nm6104351',
    'nm6884171',
    'nm8404957',
    'nm9693155']},
  'tt0053318': {'title': 'Suddenly, Last Summer (1959)',
   'box_office': 9000000.0,
   'actor_ids': ['nm0000072',
    'nm0109984',
    'nm0131537',
    'nm0730461',
    'nm0898380',
    'nm0931783',
    'nm0949697']},
  'tt0053436': {'title': 'Watusi (1959)',
   'box_office': 1545000.0,
   'actor_ids': ['nm0204186', 'nm0253359', 'nm0860574', 'nm0946103']},
  'tt0053571': {'title': 'The Adventures of Huckleberry Finn (1960)',
   'box_office': 2750000.0,
   'actor_ids': ['nm0370117', 'nm0388155', 'nm0600911']},
  'tt0053580': {'title': 'The Alamo (1960)',
   'box_office': 7900000.0,
   'actor_ids': ['nm0000811',
    'nm0001847',
    'nm0037364',
    'nm0096458',
    'nm0199583',
    'nm0226109',
    'nm0354377',
    'nm0490639',
    'nm0529036',
    'nm0639613',
    'nm0655774',
    'nm0730574',
    'nm0915511',
    'nm0932629',
    'nm0941401']},
  'tt0053583': {'title': 'All the Young Men (1960)',
   'box_office': 2000000.0,
   'actor_ids': ['nm0205156',
    'nm0423959',
    'nm0544202',
    'nm0703736',
    'nm0821146',
    'nm0874995']},
  'tt0053604': {'title': 'The Apartment (1960)',
   'box_office': 25000000.0,
   'actor_ids': ['nm0000493',
    'nm0000511',
    'nm0006037',
    'nm0010944',
    'nm0251758',
    'nm0255653',
    'nm0258599',
    'nm0381643',
    'nm0389152',
    'nm0390516',
    'nm0417055',
    'nm0450448',
    'nm0472816',
    'nm0478093',
    'nm0507081',
    'nm0534045',
    'nm0712844',
    'nm0786252',
    'nm0790064',
    'nm0828653',
    'nm0858412',
    'nm0914018',
    'nm0924668',
    'nm7016174']},
  'tt0053644': {'title': 'The Bellboy (1960)',
   'box_office': 10000000.0,
   'actor_ids': ['nm0037605',
    'nm0059136',
    'nm0078962',
    'nm0139699',
    'nm0165667',
    'nm0313959',
    'nm0314778',
    'nm0336865',
    'nm0347971',
    'nm0484709',
    'nm0585448',
    'nm0743241',
    'nm0762370',
    'nm0779145',
    'nm0787232',
    'nm0822427',
    'nm0836559',
    'nm0855944',
    'nm1019864',
    'nm10638365',
    'nm1110822',
    'nm1111708',
    'nm1713660',
    'nm1714660',
    'nm1715301',
    'nm1715360',
    'nm1715432',
    'nm1716668',
    'nm1716883',
    'nm1716968',
    'nm1717029',
    'nm1717056',
    'nm1717420',
    'nm7084742']},
  'tt0053690': {'title': 'Can-Can (1960)',
   'box_office': 8400000.0,

In [ ]:
game_logic.load_data('../data/game_data.pkl')